FROM python:3.12-alpine

LABEL mantainer="cob0"\
      org.opencontainers.image.authors="cob0 <cob0@tutanota.com>"\
      org.opencontainers.image.title="dep-scan-threshold-analyzer"\
      org.opencontainers.image.description="A binary tool that verifies if vulnerability reports generated by dep-scan comply with predefined security thresholds. It outputs OK if the vulnerabilities are within the threshold or FAIL if they exceed the allowed values."\
      org.opencontainers.image.source="https://github.com/cob0/dep-scan-threshold-analyzer"\
      org.opencontainers.image.version="1.0.0"\
      org.opencontainers.image.licenses=GPLv3

COPY argparser /opt/dep-scan-threshold-analyzer/argparser
COPY depscan /opt/dep-scan-threshold-analyzer/depscan
COPY log /opt/dep-scan-threshold-analyzer/log
COPY dep_scan_threshold_analyzer.py /opt/dep-scan-threshold-analyzer

WORKDIR /opt/dep-scan-threshold-analyzer

ENTRYPOINT [ "python", "-u" ]