services:
  dep-scan-threshold-analyzer:
    build: .
    volumes:
      - $PWD/reports:/opt/dep-scan-threshold-analyzer/reports:Z
    network_mode: none
    entrypoint: python -u
    command: dep_scan_threshold_analyzer.py -f reports/sbom-java.vdr.json -t 5