name: Run dependency scanner
run-name: ${{ github.actor }} is running dependency scanner

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  run-dependency-scanner:
    runs-on: ubuntu-latest
    environment: Default environment
    permissions:
      packages: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run dependency scanner
        uses: ./.github/dep-scan-action
        with:
          src: .
          project_type: docker
        env:
          VDB_HOME: ${{ github.workspace }}/db
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Debug reports folder
        run: ls -lha reports/ && cat reports/sbom-python.json
      - name: Check dependency reports
        uses: ./.github/dep-scan-threshold-analyzer-action
        with:
          report_file: '/github/workspace/reports/sbom-python.vdr.json'
          threshold: '7.0'