name: Main base workflow
run-name: ${{ github.actor }} is running main base workflow

on:
  push:
    branches:
      - main

jobs:
  build-main-branch:
    runs-on: ubuntu-latest
    environment: Default
    steps:
      - name: to be define
        run: echo "to be define"
